# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
diff_levenshtein <- function(obj) {
    .Call(`_diffmatchpatch_diff_levenshtein`, obj)
}

#' @export
diff_to_delta <- function(obj) {
    .Call(`_diffmatchpatch_diff_to_delta`, obj)
}

#' @export
diff_from_delta <- function(x, delta) {
    .Call(`_diffmatchpatch_diff_from_delta`, x, delta)
}

#' @export
diff_to_html <- function(obj) {
    .Call(`_diffmatchpatch_diff_to_html`, obj)
}

#' @export
diff_to_patch <- function(obj) {
    .Call(`_diffmatchpatch_diff_to_patch`, obj)
}

#' @export
diff_text_source <- function(obj) {
    .Call(`_diffmatchpatch_diff_text_source`, obj)
}

#' @export
diff_text_dest <- function(obj) {
    .Call(`_diffmatchpatch_diff_text_dest`, obj)
}

#' @export
diff_make <- function(x, y, cleanup = "semantic", checklines = TRUE) {
    .Call(`_diffmatchpatch_diff_make`, x, y, cleanup, checklines)
}

#' @rdname match
#'
#' @title Fuzzy matching of a text string
#'
#' @description Locate the best instance of `pattern` in the `text` near `loc` using the
#' Bitap algorithm.Returns `-1` if no match found. Assumes R's typical 1-based indexing for `loc` 
#' and the returned value.
#'
#' This algorithm makes use of the `match_distance` and `match_threshold` options to determine 
#' the match.
#'
#' Candidate matches are scored based on a) the number of spelling differences between the pattern
#' and the text and b) the distance between the candidate match and the expected location. The 
#' `match_distance` option determines the relative importance of these two metrics.
#' 
#' @param text The text to search.
#' @param pattern The pattern to search for.
#' @param loc The location to search around.
#' 
#' @return Best match index or -1.
#' 
#' @export
match_find <- function(text, pattern, loc) {
    .Call(`_diffmatchpatch_match_find`, text, pattern, loc)
}

#' @export
get_options <- function() {
    .Call(`_diffmatchpatch_get_options`)
}

#' @export
set_options <- function(opts) {
    invisible(.Call(`_diffmatchpatch_set_options`, opts))
}

#' @rdname patch
#' 
#' @title Create and apply patches to a text string
#'
#' @description `patch_make()` computes a list of patches to turn the source string (`x`) into the
#' destination string (`y`).
#'
#' @param x The source string
#' @param y The destination string
#' 
#' @return `patch_make()` returns a string representation of the patch(es).
#'
#' @export
patch_make <- function(x, y) {
    .Call(`_diffmatchpatch_patch_make`, x, y)
}

#' @rdname patch
#'
#' @description `patch_apply()` applies the `patch` to `x`.
#'
#' @param patch A string representation of the patch(es).
#'
#' @return `patch_apply()` returns the patched version of the string x, the `matches` attribute 
#' contains logical values indicating which patches were successfully applied.
#'
#' @export
patch_apply <- function(x, patch) {
    .Call(`_diffmatchpatch_patch_apply`, x, patch)
}

